// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationReq.proto

package com.geo.proto;

public final class LocationReqProto {
  private LocationReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    boolean hasAccessPoints();
    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    com.geo.proto.LocationReqProto.AccessPoints getAccessPoints();
    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    com.geo.proto.LocationReqProto.AccessPointsOrBuilder getAccessPointsOrBuilder();
  }
  /**
   * Protobuf type {@code LocationReq}
   */
  public  static final class LocationReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationReq)
      LocationReqOrBuilder {
    // Use LocationReq.newBuilder() to construct.
    private LocationReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationReq() {
      userId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LocationReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              com.geo.proto.LocationReqProto.AccessPoints.Builder subBuilder = null;
              if (accessPoints_ != null) {
                subBuilder = accessPoints_.toBuilder();
              }
              accessPoints_ = input.readMessage(com.geo.proto.LocationReqProto.AccessPoints.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accessPoints_);
                accessPoints_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geo.proto.LocationReqProto.internal_static_LocationReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geo.proto.LocationReqProto.internal_static_LocationReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geo.proto.LocationReqProto.LocationReq.class, com.geo.proto.LocationReqProto.LocationReq.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSPOINTS_FIELD_NUMBER = 2;
    private com.geo.proto.LocationReqProto.AccessPoints accessPoints_;
    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    public boolean hasAccessPoints() {
      return accessPoints_ != null;
    }
    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    public com.geo.proto.LocationReqProto.AccessPoints getAccessPoints() {
      return accessPoints_ == null ? com.geo.proto.LocationReqProto.AccessPoints.getDefaultInstance() : accessPoints_;
    }
    /**
     * <code>optional .AccessPoints accessPoints = 2;</code>
     */
    public com.geo.proto.LocationReqProto.AccessPointsOrBuilder getAccessPointsOrBuilder() {
      return getAccessPoints();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (accessPoints_ != null) {
        output.writeMessage(2, getAccessPoints());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (accessPoints_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAccessPoints());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geo.proto.LocationReqProto.LocationReq)) {
        return super.equals(obj);
      }
      com.geo.proto.LocationReqProto.LocationReq other = (com.geo.proto.LocationReqProto.LocationReq) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (hasAccessPoints() == other.hasAccessPoints());
      if (hasAccessPoints()) {
        result = result && getAccessPoints()
            .equals(other.getAccessPoints());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (hasAccessPoints()) {
        hash = (37 * hash) + ACCESSPOINTS_FIELD_NUMBER;
        hash = (53 * hash) + getAccessPoints().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.LocationReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geo.proto.LocationReqProto.LocationReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationReq)
        com.geo.proto.LocationReqProto.LocationReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geo.proto.LocationReqProto.internal_static_LocationReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geo.proto.LocationReqProto.internal_static_LocationReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geo.proto.LocationReqProto.LocationReq.class, com.geo.proto.LocationReqProto.LocationReq.Builder.class);
      }

      // Construct using com.geo.proto.LocationReqProto.LocationReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        if (accessPointsBuilder_ == null) {
          accessPoints_ = null;
        } else {
          accessPoints_ = null;
          accessPointsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geo.proto.LocationReqProto.internal_static_LocationReq_descriptor;
      }

      public com.geo.proto.LocationReqProto.LocationReq getDefaultInstanceForType() {
        return com.geo.proto.LocationReqProto.LocationReq.getDefaultInstance();
      }

      public com.geo.proto.LocationReqProto.LocationReq build() {
        com.geo.proto.LocationReqProto.LocationReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.geo.proto.LocationReqProto.LocationReq buildPartial() {
        com.geo.proto.LocationReqProto.LocationReq result = new com.geo.proto.LocationReqProto.LocationReq(this);
        result.userId_ = userId_;
        if (accessPointsBuilder_ == null) {
          result.accessPoints_ = accessPoints_;
        } else {
          result.accessPoints_ = accessPointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geo.proto.LocationReqProto.LocationReq) {
          return mergeFrom((com.geo.proto.LocationReqProto.LocationReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geo.proto.LocationReqProto.LocationReq other) {
        if (other == com.geo.proto.LocationReqProto.LocationReq.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasAccessPoints()) {
          mergeAccessPoints(other.getAccessPoints());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.geo.proto.LocationReqProto.LocationReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.geo.proto.LocationReqProto.LocationReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private com.geo.proto.LocationReqProto.AccessPoints accessPoints_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.geo.proto.LocationReqProto.AccessPoints, com.geo.proto.LocationReqProto.AccessPoints.Builder, com.geo.proto.LocationReqProto.AccessPointsOrBuilder> accessPointsBuilder_;
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public boolean hasAccessPoints() {
        return accessPointsBuilder_ != null || accessPoints_ != null;
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public com.geo.proto.LocationReqProto.AccessPoints getAccessPoints() {
        if (accessPointsBuilder_ == null) {
          return accessPoints_ == null ? com.geo.proto.LocationReqProto.AccessPoints.getDefaultInstance() : accessPoints_;
        } else {
          return accessPointsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public Builder setAccessPoints(com.geo.proto.LocationReqProto.AccessPoints value) {
        if (accessPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accessPoints_ = value;
          onChanged();
        } else {
          accessPointsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public Builder setAccessPoints(
          com.geo.proto.LocationReqProto.AccessPoints.Builder builderForValue) {
        if (accessPointsBuilder_ == null) {
          accessPoints_ = builderForValue.build();
          onChanged();
        } else {
          accessPointsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public Builder mergeAccessPoints(com.geo.proto.LocationReqProto.AccessPoints value) {
        if (accessPointsBuilder_ == null) {
          if (accessPoints_ != null) {
            accessPoints_ =
              com.geo.proto.LocationReqProto.AccessPoints.newBuilder(accessPoints_).mergeFrom(value).buildPartial();
          } else {
            accessPoints_ = value;
          }
          onChanged();
        } else {
          accessPointsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public Builder clearAccessPoints() {
        if (accessPointsBuilder_ == null) {
          accessPoints_ = null;
          onChanged();
        } else {
          accessPoints_ = null;
          accessPointsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public com.geo.proto.LocationReqProto.AccessPoints.Builder getAccessPointsBuilder() {
        
        onChanged();
        return getAccessPointsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      public com.geo.proto.LocationReqProto.AccessPointsOrBuilder getAccessPointsOrBuilder() {
        if (accessPointsBuilder_ != null) {
          return accessPointsBuilder_.getMessageOrBuilder();
        } else {
          return accessPoints_ == null ?
              com.geo.proto.LocationReqProto.AccessPoints.getDefaultInstance() : accessPoints_;
        }
      }
      /**
       * <code>optional .AccessPoints accessPoints = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.geo.proto.LocationReqProto.AccessPoints, com.geo.proto.LocationReqProto.AccessPoints.Builder, com.geo.proto.LocationReqProto.AccessPointsOrBuilder> 
          getAccessPointsFieldBuilder() {
        if (accessPointsBuilder_ == null) {
          accessPointsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.geo.proto.LocationReqProto.AccessPoints, com.geo.proto.LocationReqProto.AccessPoints.Builder, com.geo.proto.LocationReqProto.AccessPointsOrBuilder>(
                  getAccessPoints(),
                  getParentForChildren(),
                  isClean());
          accessPoints_ = null;
        }
        return accessPointsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LocationReq)
    }

    // @@protoc_insertion_point(class_scope:LocationReq)
    private static final com.geo.proto.LocationReqProto.LocationReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geo.proto.LocationReqProto.LocationReq();
    }

    public static com.geo.proto.LocationReqProto.LocationReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocationReq>
        PARSER = new com.google.protobuf.AbstractParser<LocationReq>() {
      public LocationReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LocationReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationReq> getParserForType() {
      return PARSER;
    }

    public com.geo.proto.LocationReqProto.LocationReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccessPointsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AccessPoints)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */
    int getPointsCount();
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */
    boolean containsPoints(
        java.lang.String key);
    /**
     * Use {@link #getPointsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Float>
    getPoints();
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Float>
    getPointsMap();
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    float getPointsOrDefault(
        java.lang.String key,
        float defaultValue);
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    float getPointsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code AccessPoints}
   */
  public  static final class AccessPoints extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AccessPoints)
      AccessPointsOrBuilder {
    // Use AccessPoints.newBuilder() to construct.
    private AccessPoints(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccessPoints() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AccessPoints(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = com.google.protobuf.MapField.newMapField(
                    PointsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
              points = input.readMessage(
                  PointsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              points_.getMutableMap().put(points.getKey(), points.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geo.proto.LocationReqProto.internal_static_AccessPoints_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPoints();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geo.proto.LocationReqProto.internal_static_AccessPoints_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geo.proto.LocationReqProto.AccessPoints.class, com.geo.proto.LocationReqProto.AccessPoints.Builder.class);
    }

    public static final int POINTS_FIELD_NUMBER = 1;
    private static final class PointsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Float> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Float>newDefaultInstance(
                  com.geo.proto.LocationReqProto.internal_static_AccessPoints_PointsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.FLOAT,
                  0F);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Float> points_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
    internalGetPoints() {
      if (points_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PointsDefaultEntryHolder.defaultEntry);
      }
      return points_;
    }

    public int getPointsCount() {
      return internalGetPoints().getMap().size();
    }
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    public boolean containsPoints(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPoints().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPointsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float> getPoints() {
      return getPointsMap();
    }
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Float> getPointsMap() {
      return internalGetPoints().getMap();
    }
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    public float getPointsOrDefault(
        java.lang.String key,
        float defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetPoints().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, float&gt; points = 1;</code>
     */

    public float getPointsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetPoints().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.Float> entry
           : internalGetPoints().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
        points = PointsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, points);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Float> entry
           : internalGetPoints().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
        points = PointsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, points);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geo.proto.LocationReqProto.AccessPoints)) {
        return super.equals(obj);
      }
      com.geo.proto.LocationReqProto.AccessPoints other = (com.geo.proto.LocationReqProto.AccessPoints) obj;

      boolean result = true;
      result = result && internalGetPoints().equals(
          other.internalGetPoints());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetPoints().getMap().isEmpty()) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPoints().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geo.proto.LocationReqProto.AccessPoints parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geo.proto.LocationReqProto.AccessPoints prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AccessPoints}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AccessPoints)
        com.geo.proto.LocationReqProto.AccessPointsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geo.proto.LocationReqProto.internal_static_AccessPoints_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetPoints();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutablePoints();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geo.proto.LocationReqProto.internal_static_AccessPoints_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geo.proto.LocationReqProto.AccessPoints.class, com.geo.proto.LocationReqProto.AccessPoints.Builder.class);
      }

      // Construct using com.geo.proto.LocationReqProto.AccessPoints.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutablePoints().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geo.proto.LocationReqProto.internal_static_AccessPoints_descriptor;
      }

      public com.geo.proto.LocationReqProto.AccessPoints getDefaultInstanceForType() {
        return com.geo.proto.LocationReqProto.AccessPoints.getDefaultInstance();
      }

      public com.geo.proto.LocationReqProto.AccessPoints build() {
        com.geo.proto.LocationReqProto.AccessPoints result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.geo.proto.LocationReqProto.AccessPoints buildPartial() {
        com.geo.proto.LocationReqProto.AccessPoints result = new com.geo.proto.LocationReqProto.AccessPoints(this);
        int from_bitField0_ = bitField0_;
        result.points_ = internalGetPoints();
        result.points_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geo.proto.LocationReqProto.AccessPoints) {
          return mergeFrom((com.geo.proto.LocationReqProto.AccessPoints)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geo.proto.LocationReqProto.AccessPoints other) {
        if (other == com.geo.proto.LocationReqProto.AccessPoints.getDefaultInstance()) return this;
        internalGetMutablePoints().mergeFrom(
            other.internalGetPoints());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.geo.proto.LocationReqProto.AccessPoints parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.geo.proto.LocationReqProto.AccessPoints) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Float> points_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
      internalGetPoints() {
        if (points_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PointsDefaultEntryHolder.defaultEntry);
        }
        return points_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
      internalGetMutablePoints() {
        onChanged();;
        if (points_ == null) {
          points_ = com.google.protobuf.MapField.newMapField(
              PointsDefaultEntryHolder.defaultEntry);
        }
        if (!points_.isMutable()) {
          points_ = points_.copy();
        }
        return points_;
      }

      public int getPointsCount() {
        return internalGetPoints().getMap().size();
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public boolean containsPoints(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetPoints().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPointsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Float> getPoints() {
        return getPointsMap();
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Float> getPointsMap() {
        return internalGetPoints().getMap();
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public float getPointsOrDefault(
          java.lang.String key,
          float defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Float> map =
            internalGetPoints().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public float getPointsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Float> map =
            internalGetPoints().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPoints() {
        getMutablePoints().clear();
        return this;
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public Builder removePoints(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutablePoints().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Float>
      getMutablePoints() {
        return internalGetMutablePoints().getMutableMap();
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */
      public Builder putPoints(
          java.lang.String key,
          float value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        getMutablePoints().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, float&gt; points = 1;</code>
       */

      public Builder putAllPoints(
          java.util.Map<java.lang.String, java.lang.Float> values) {
        getMutablePoints().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AccessPoints)
    }

    // @@protoc_insertion_point(class_scope:AccessPoints)
    private static final com.geo.proto.LocationReqProto.AccessPoints DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geo.proto.LocationReqProto.AccessPoints();
    }

    public static com.geo.proto.LocationReqProto.AccessPoints getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccessPoints>
        PARSER = new com.google.protobuf.AbstractParser<AccessPoints>() {
      public AccessPoints parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AccessPoints(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccessPoints> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccessPoints> getParserForType() {
      return PARSER;
    }

    public com.geo.proto.LocationReqProto.AccessPoints getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessPoints_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccessPoints_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessPoints_PointsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccessPoints_PointsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LocationReq.proto\"B\n\013LocationReq\022\016\n\006us" +
      "erId\030\001 \001(\t\022#\n\014accessPoints\030\002 \001(\0132\r.Acces" +
      "sPoints\"h\n\014AccessPoints\022)\n\006points\030\001 \003(\0132" +
      "\031.AccessPoints.PointsEntry\032-\n\013PointsEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\002:\0028\001B!\n\rcom" +
      ".geo.protoB\020LocationReqProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LocationReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationReq_descriptor,
        new java.lang.String[] { "UserId", "AccessPoints", });
    internal_static_AccessPoints_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccessPoints_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccessPoints_descriptor,
        new java.lang.String[] { "Points", });
    internal_static_AccessPoints_PointsEntry_descriptor =
      internal_static_AccessPoints_descriptor.getNestedTypes().get(0);
    internal_static_AccessPoints_PointsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccessPoints_PointsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
